// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pluyitdaouytvagrybhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdXlpdGRhb3V5dHZhZ3J5YmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjM4MjUsImV4cCI6MjA2MDA5OTgyNX0.MIYSj51zdx7-TPee2S6kN--9CGStXw-QQdDgmAS0D0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);